---
language: python
python: "2.7"

# Use the new container infrastructure
sudo: false

# Install ansible
addons:
  apt:
    packages:
    - python-pip

install:
  # Install ansible
  - pip install ansible ansible-lint

  # patch ansible-lint issue 250
  - sed -i '/^\s*_jinja = re\.compile([^),]*)/ s/)\s*$/, re.DOTALL)/' `python -c "import os, ansiblelint; print(os.path.dirname(os.path.abspath(ansiblelint.__file__))+'/rules/UsingBareVariablesIsDeprecatedRule.py')"`

  # Check ansible version
  - ansible --version

  # Install python module and role dependencies
  - test -f requirements.txt && pip install -r requirements.txt
  - test -f requirements.yml && ansible-galaxy install -p tests/roles -r requirements.yml

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../' >ansible.cfg

script:
  # Basic role syntax check
  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check
  - ansible-lint .
  - ansible-lint tests/test.yml

  - ansible-playbook tests/test.yml -i tests/inventory
  - rm ~/.ssh/known_hosts
  - ansible-playbook tests/test.yml -i tests/inventory
  - ansible-playbook tests/test.yml -i tests/inventory
  - rm ~/.ssh/known_hosts
  - ansible-playbook tests/test.yml -i tests/inventory --become
  - ansible-playbook tests/test.yml -i tests/inventory --become

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
