---
os: linux

# xenial --> openssh 7.2
dist: xenial

language: python
python:
- 2.7
- 3.5

jobs:
  include:
  # bionic --> openssh 7.6
  - dist: bionic
    python: 2.7
  - dist: bionic
    python: 3.5

# Install ansible
addons:
  apt:
    packages:
    - python-pip

install:
  # Install ansible
  - pip install ansible "ansible-lint>=4.2.0"

  # Check ansible version
  - ansible --version

  # Install python module and role dependencies
  - test -f requirements.txt && pip install -r requirements.txt
  - test -f requirements.yml && ansible-galaxy install -p tests/roles -r requirements.yml

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../' >ansible.cfg

  - ssh -V

script:
  # Basic role syntax check
  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check
  - ansible-lint .
  - ansible-lint tests/test.yml

  - ansible-playbook tests/test.yml -i tests/inventory
  - test ! -f ~/.ssh/known_hosts || rm ~/.ssh/known_hosts
  - ansible-playbook tests/test.yml -i tests/inventory
  - ansible-playbook tests/test.yml -i tests/inventory
  - test ! -f ~/.ssh/known_hosts || rm ~/.ssh/known_hosts
  - ansible-playbook tests/test.yml -i tests/inventory --become
  - ansible-playbook tests/test.yml -i tests/inventory --become

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
