---
- name: search ssh fingerprints
  connection: local
  with_items: >
    {{ [ '/etc/ssh/ssh_known_hosts',
         '~/.ssh/known_hosts' | expanduser ]
       | select('exists')
       | list }}
  command: >
    ssh-keygen
    -F {{ ansible_host | d(inventory_hostname) }}
    -f {{ item }}
  register: local_keygen
  failed_when: local_keygen.stderr != ''
  changed_when: False

- block:
  - name: detect supported ssh fingerprint types
    connection: local
    run_once: True
    with_items: [ ed25519, rsa, ecdsa, dsa, rsa1 ]
    command: ssh-keyscan -t {{ item }}
    register: local_keyscan_types
    failed_when: local_keyscan_types.stderr | match('unknown key type.*')
    ignore_errors: True
    changed_when: False

  - name: fetch remote ssh fingerprints
    connection: local
    command: >
      ssh-keyscan -H
      -t {{ local_keyscan_types.results | rejectattr('failed') | map(attribute='item') | join(',') | d('fail') }}
      -p {{ ansible_port | d(local_ansible_config['defaults/remote_port']) | d(22) }}
      {{ ansible_host | d(inventory_hostname) }}
    register: local_keyscan
    failed_when: local_keyscan.rc != 0 or local_keyscan.stdout == ''
    changed_when: False

  - name: accept new ssh fingerprints
    connection: local
    with_items: "{{ local_keyscan.stdout_lines | d([]) }}"
    known_hosts:
      name: "{{ ansible_host | d(inventory_hostname) }}"
      key: "{{ item }}"
      state: present
      #hash_host: True

  - name: the file mode of user known_hosts is 0600
    connection: local
    run_once: True
    when: "'~/.ssh/known_hosts' | expanduser | exists"
    file:
      path: "{{ '~/.ssh/known_hosts' | expanduser }}"
      mode: 0600

  when: local_keygen.results | reject('skipped') | rejectattr('rc', 'equalto', 1) | list | length == 0
