---
- name: search ssh fingerprints
  delegate_to: localhost
  become: False
  become_user: "{{ ansible_user | d(lookup('id', 'euname'), True) }}"
  vars:
  - ansible_become: False
  - ansible_become_user: "{{ ansible_user | d(lookup('id', 'euname'), True) }}"
  with_items: >
    {{ [ '/etc/ssh/ssh_known_hosts',
         '~/.ssh/known_hosts' | expanduser ]
       | select('exists')
       | list }}
  raw: >-
    ssh-keygen
    -F {{ [ (ansible_port | d(22) == 22) | ternary('', '['),
            hostvars[inventory_hostname].ansible_host | d(inventory_hostname),
            (ansible_port | d(22) == 22) | ternary('', ']:'),
            (ansible_port | d(22) == 22) | ternary('', ansible_port)
          ] | join('') }} \
    -f {{ item }}
  register: local_keygen
  failed_when: local_keygen.stderr != ''
  changed_when: False

- block:
  - name: detect supported ssh fingerprint types
    delegate_to: localhost
    become: False
    become_user: "{{ ansible_user | d(lookup('id', 'euname'), True) }}"
    vars:
    - ansible_become: False
    - ansible_become_user: "{{ ansible_user | d(lookup('id', 'euname'), True) }}"
    run_once: True
    with_items: [ ed25519, rsa, ecdsa, dsa, rsa1 ]
    raw: ssh-keyscan -t {{ item }}
    register: local_keyscan_types
    failed_when: local_keyscan_types.stderr | match('unknown key type.*')
    ignore_errors: True
    changed_when: False

  - name: fetch remote ssh fingerprints
    delegate_to: localhost
    become: False
    become_user: "{{ ansible_user | d(lookup('id', 'euname'), True) }}"
    vars:
    - ansible_become: False
    - ansible_become_user: "{{ ansible_user | d(lookup('id', 'euname'), True) }}"
    raw: >-
      ssh-keyscan {{ (ansible_port | d(22) == 22) | ternary('-H', '') }}
      -t {{ local_keyscan_types.results | rejectattr('failed') | map(attribute='item') | join(',') | d('fail') }}
      -p {{ ansible_port | d(22) }}
      {{ hostvars[inventory_hostname].ansible_host | d(inventory_hostname) }}
    register: local_keyscan
    failed_when: local_keyscan.rc != 0 or local_keyscan.stdout == ''
    changed_when: False

  - name: accept new ssh fingerprints
    delegate_to: localhost
    become: False
    become_user: "{{ ansible_user | d(lookup('id', 'euname'), True) }}"
    vars:
    - ansible_become: False
    - ansible_become_user: "{{ ansible_user | d(lookup('id', 'euname'), True) }}"
    with_items: "{{ local_keyscan.stdout_lines
                    | d([])
                    | map('regex_replace',
                          (ansible_port | d(22) == 22) | ternary('^(.)$', '^([^[ ]*) '),
                          '[\\1]:' + (ansible_port | d(22) | string) + ' ')
                    | list }}"
    known_hosts:
      name: >-
        {{ [ (ansible_port | d(22) == 22) | ternary('', '['),
             hostvars[inventory_hostname].ansible_host | d(inventory_hostname),
             (ansible_port | d(22) == 22) | ternary('', ']:'),
             (ansible_port | d(22) == 22) | ternary('', ansible_port)
           ] | join('') }}
      key: "{{ item }}"
      state: present
      #hash_host: True

  - name: user known_hosts mode is 0600
    delegate_to: localhost
    become: False
    become_user: "{{ ansible_user | d(lookup('id', 'euname'), True) }}"
    vars:
    - ansible_become: False
    - ansible_become_user: "{{ ansible_user | d(lookup('id', 'euname'), True) }}"
    run_once: True
    when: "'~/.ssh/known_hosts' | expanduser | exists"
    file:
      path: "{{ '~/.ssh/known_hosts' | expanduser }}"
      owner: "{{ lookup('id', 'euname') }}"
      mode: 'u=rw,g=,o='

  when: local_keygen.results | reject('skipped') | map(attribute='rc') | difference([1]) | list | length == 0
